name: analytics
description: Simple analytics library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

resolution: workspace

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: 1.19.1

  # Firebase
  firebase_analytics: ^11.5.0

  # Local Packages
  logger:
    path: ../logger
  
  # Code generation
  freezed_annotation: ^3.1.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: 5.5.0
  build_runner: ^2.6.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true