include: package:sizzle_lints/lints.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  exclude:
    - "lib/src/core/localization/generated/**"
    - "**/*.*.dart"
    - "**/generated/**"

dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml
