name: error_reporter
description: Error reporter
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger:
    path: ../logger
  sentry_flutter: 8.14.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.5.3
